// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiuSuDSnBuF-ShFVMnHf-8Cfar-Wp1ZM',
    appId: '1:7812420141:web:50120a12518d073de49ea4',
    messagingSenderId: '7812420141',
    projectId: 'reservation-b9548',
    authDomain: 'reservation-b9548.firebaseapp.com',
    storageBucket: 'reservation-b9548.firebasestorage.app',
    measurementId: 'G-Z3T3QFGW8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChTxUyqniW8ovyIsv9Q-owSN_9nl95YGY',
    appId: '1:7812420141:android:cda59752d85fea74e49ea4',
    messagingSenderId: '7812420141',
    projectId: 'reservation-b9548',
    storageBucket: 'reservation-b9548.firebasestorage.app',
  );
}
